title: NetSci 2025
description: International School and Conference on Network Science

url: https://NetSci2025.github.io/test

# Locally
baseurl: ""
#remote_theme: piazzai/jekyll-nagymaros

# Online
#baseurl: "/test"
#theme: jekyll-nagymaros


copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
  - run.sh
